package ws2j.userservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-10-12T15:39:23.064+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://api.dubbo.boot/", name = "UserServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface UserServicePortType {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findUser", targetNamespace = "http://api.dubbo.boot/", className = "ws2j.userservice.FindUser")
    @WebMethod
    @ResponseWrapper(localName = "findUserResponse", targetNamespace = "http://api.dubbo.boot/", className = "ws2j.userservice.FindUserResponse")
    public ws2j.userservice.User findUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addUser", targetNamespace = "http://api.dubbo.boot/", className = "ws2j.userservice.AddUser")
    @WebMethod
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://api.dubbo.boot/", className = "ws2j.userservice.AddUserResponse")
    public java.util.List<ws2j.userservice.User> addUser(
        @WebParam(name = "arg0", targetNamespace = "")
        ws2j.userservice.User arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://api.dubbo.boot/", className = "ws2j.userservice.UpdateUser")
    @WebMethod
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://api.dubbo.boot/", className = "ws2j.userservice.UpdateUserResponse")
    public java.util.List<ws2j.userservice.User> updateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        ws2j.userservice.User arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllUsers", targetNamespace = "http://api.dubbo.boot/", className = "ws2j.userservice.FindAllUsers")
    @WebMethod
    @ResponseWrapper(localName = "findAllUsersResponse", targetNamespace = "http://api.dubbo.boot/", className = "ws2j.userservice.FindAllUsersResponse")
    public java.util.List<ws2j.userservice.User> findAllUsers();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://api.dubbo.boot/", className = "ws2j.userservice.DeleteUser")
    @WebMethod
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://api.dubbo.boot/", className = "ws2j.userservice.DeleteUserResponse")
    public java.util.List<ws2j.userservice.User> deleteUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );
}
